### ISSUE TITLE
[certificate] Invalid certificate with old curl version

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli-dl#3]
We may want to use Scalingo wildcard certificate for this domain name to prevent this kind of issue with old curl version.

Talk in `#support`: https://scalingo.slack.com/archives/C03T384J3/p1635318180001200
Customer report: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700044711

**Comment by brandon-welsch** [comment]
Another customer that have the issue: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/3379738/conversations/12375700056410
